title: Hay Day IT Bot
description: Documentazione ufficiale del bot italiano di Hay Day.

# Configurazione URL fondamentale
url: "https://jordanmerli.github.io"
baseurl: "/hayday-docs"

# Configurazione Tema
remote_theme: just-the-docs/just-the-docs